feat: update gorelease

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,2 +1,13 @@
-npx lint-staged
+#!/bin/sh
 
+npx lint-staged
+if [ $? -ne 0 ]; then
+    echo "Linting failed, commit aborted."
+    exit 1
+fi
+
+goreleaser check
+if [ $? -ne 0 ]; then
+    echo "GoReleaser check failed, commit aborted."
+    exit 1
+fi
